'''
Copyright 2009 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
'''

noun_cards = (
     ['Android', 'Google', 'App Inventor', 'Cell Phones', 'The Internet', 'MIT',
     'Mountain View, CA', 'Cambridge, MA', 'Hero', 'Dream',
'A Bull Fight', 
'A Cabin In The Woods', 
'A Can Of Worms', 
'A Car Crash', 
'A Cheap Motel', 
'A Cookbook', 
'A Crawl Space', 
'A Crown', 
'A Desert', 
'A Dollar', 
'A Dozen Red Roses', 
'A Fairy', 
'A Few Good Men', 
'A Flat Tire', 
'A Fool & His Money', 
'A Forest', 
'A French Maid', 
'A Full Moon', 
'A Funeral', 
'A Giant', 
'A Haunted House', 
'A High School Bathroom', 
'A Hole In One', 
'A Honeymoon', 
'A King', 
'A Leaky Boat', 
'A Little White Lie', 
'A Locker Room', 
'A Log Cabin', 
'A Mermaid', 
'A Microwave Oven', 
'A Million Dollars', 
'A Morgue', 
'A Movie Theater', 
'A Mummy', 
'A Nine Iron', 
'A Parade', 
'A Piano', 
'A Pile Of Leaves', 
'A Prince', 
'A Princess', 
'A Queen', 
'A Refrigerator', 
'A Ringing In My Ears', 
'A Saw', 
'A School Bus', 
'A School Cafeteria', 
'A School Dance', 
'A Spare Tire', 
'A Submarine', 
'A Sunrise', 
'A Sunset', 
'A Surprise', 
'A Swimming Pool', 
'A Tree House', 
'A Used Car Lot', 
'A Volcano', 
'Abbot & Costello', 
'Abraham Lincoln', 
'Abraham Lincoln', 
'Actors', 
'Actresses', 
'Adam & Eve', 
'Adam Sandler', 
'Adolph Hitler', 
'Africa', 
'AIDS', 
'Airline Food', 
'Airplane', 
'Airplanes', 
'Al Pacino', 
'Aladdin', 
'Alan Greenspan', 
'Alaska', 
'Albert Einstein', 
'Alfred Hitchcock', 
'Alien Abductions', 
'Aliens', 
'Alligators', 
'AM & FM', 
'Americans', 
'Amputations', 
'Amsterdam', 
'An Igloo', 
'Ancient Rome', 
'Andy Warhol', 
'Angry Hornets', 
'Anna & The King', 
'Anna Kournikova', 
'Anne Frank', 
'Antarctica', 
'Anthony Hopkins', 
'Anthrax', 
'Antiques Roadshow', 
'Antony & Cleopatra', 
'Ants', 
'Apple Juice', 
'Apple Pie', 
'Apples', 
'Apples & Oranges', 
'Aristotle', 
'Arm & A Leg', 
'Armadillo', 
'Armed Robbery', 
'Arnold Schwarzenegger', 
'Aroma Therapy', 
'Arsenic & Old Lace', 
'Artists', 
'Assault & Battery', 
'Assembly Lines', 
'Astronauts', 
'At My Parent\'s House', 
'Atlantis', 
'Atomic Bombs', 
'Attack On Pearl Harbor', 
'Austin Powers', 
'Australian Outback', 
'Babe Ruth', 
'Babies', 
'Baby Dolls', 
'Baby Food', 
'Baby Showers', 
'Babysitters', 
'Backstreet Boys', 
'Backyards', 
'Bacon', 
'Bad Dogs', 
'Bad Dreams', 
'Bagels And Lox', 
'Bagpipes', 
'Baked Beans', 
'Baked Potatoes', 
'Baking Cookies', 
'Bald Eagles', 
'Ball & Chain', 
'Ballerinas', 
'Balloons', 
'Ballroom Dancing', 
'Bananas', 
'Band-Aids', 
'Bangkok', 
'Bankruptcy', 
'Barbara Walters', 
'Barbed Wire', 
'Barbershops', 
'Barbie & Ken', 
'Barbie Dolls', 
'Barfing', 
'Barney', 
'Bart Simpson', 
'Baseball', 
'Baseball Games', 
'Baseball Fields', 
'Basketball', 
'Bates Motel', 
'Batman', 
'Batman & Robin', 
'Bats', 
'Bats & Balls', 
'BB Guns', 
'Beach Balls', 
'Beach Parties', 
'Beanbag Chairs', 
'Beanie Babies', 
'Bears', 
'Beauty & The Beast', 
'Beauty And The Beast', 
'Beavis & Butt-Head', 
'Bed & Breakfast', 
'Bee Stings', 
'Beef Stew', 
'Beer', 
'Beer & Pretzels', 
'Beer Bellies', 
'Beethoven', 
'Beets', 
'Being & Nothingness', 
'Being In Love', 
'Bell-Bottoms', 
'Bells & Whistles', 
'Belt Buckles', 
'Ben Stiller', 
'Berlin - 1945', 
'Bert & Ernie', 
'Bert And Ernie', 
'Bigfoot', 
'Big Bang Theory', 
'Big Bird', 
'Big Cities', 
'Big Dogs', 
'Big Macs', 
'Bill & Ted', 
'Bill Clinton', 
'Bill Gates', 
'Bill Murray', 
'Billboards', 
'Billy Crystal', 
'Bingo', 
'Bird Watching', 
'Birds', 
'Birthday Cake', 
'Black Cats', 
'Black Holes', 
'Black Licorice', 
'Black Lingerie', 
'Black Velvet', 
'Blackouts', 
'Blizzard', 
'Blood', 
'Blood & Tears', 
'Blowing Bubbles', 
'Blowing Your Nose', 
'Blue Velvet', 
'Blueberries', 
'Board Games', 
'Boardwalk & Park Place', 
'Boats', 
'Body & Soul', 
'Body Odor', 
'Body Piercing', 
'Body Snatchers', 
'Body Surfing', 
'Bodybuilders', 
'Bonbons', 
'Bongos', 
'Bonnie & Clyde', 
'Bora Bora', 
'Bottled Water', 
'Bow & Arrows', 
'Bowling', 
'Boxing', 
'Boy Scouts', 
'Boyfriends', 
'Boys', 
'Braces', 
'Brad Pitt', 
'Brain Surgeons', 
'Brains', 
'Bread & Water', 
'Breaking & Entering', 
'Bride & Groom', 
'Britney Spears', 
'Broadway', 
'Brooks & Dunn', 
'Brothers', 
'Brothers & Sisters', 
'Bruce Willis', 
'Bruises', 
'Brushing Your Teeth', 
'Bubble Bath', 
'Bubble Gum', 
'Bubbles', 
'Buffalo', 
'Bugs', 
'Bugs Bunny', 
'Bulls & Bears', 
'Bullfighting', 
'Bullwinkle', 
'Bumble Bees', 
'Bumper Cars', 
'Bumper Stickers', 
'Bungee Jumping', 
'Bunk Beds', 
'Burger & Fries', 
'Burned Toast', 
'Bus Drivers', 
'Butter', 
'Buttons & Bows', 
'Butterflies', 
'Buying A House', 
'Buzz Lightyear', 
'Cabbage', 
'Cactus', 
'California', 
'Calvin & Hobbs', 
'Camelot', 
'Camels', 
'Cameras', 
'Campfire', 
'Camping', 
'Camping Trip', 
'Canada', 
'Canadians', 
'Candles', 
'Candy', 
'Candy Corn', 
'Canoes', 
'Captain Kirk', 
'Car Bombs', 
'Car Crash', 
'Car Horns', 
'Card Games', 
'Carl Sagan', 
'Carlos Santana', 
'Carnival Workers', 
'Carpenters', 
'Carrot & A Stick', 
'Carrots', 
'Cary Grant', 
'Casablanca', 
'Casinos', 
'Castles', 
'Castles', 
'Cat & Mouse', 
'Catfish', 
'Catherine Zeta-Jones', 
'Cats & Dogs', 
'Catsup', 
'Catsup & Mustard', 
'Cattle Ranch', 
'Cavities', 
'Cauliflower', 
'Caves', 
'Caviar', 
'CD Players', 
'Celine Dion', 
'Cell Phones', 
'Cesar Chavez', 
'Chain Letters', 
'Chain Link Fences', 
'Chains', 
'Challenger Explosion', 
'Chameleons', 
'Charging Rhinos', 
'Charles & Diana', 
'Charlie Brown', 
'Charlotte\'s Web', 
'Chat Rooms', 
'Cheerleaders', 
'Cheese', 
'Cheese Sandwich', 
'Cheesecake', 
'Cher', 
'Cherries', 
'Cherry Pie', 
'Chewing Your Fingernails', 
'Chicken Nuggets', 
'Chicago', 
'Chicken Pox', 
'Chickens', 
'Chimpanzees', 
'China', 
'Chinatown', 
'Chips & Dip', 
'Chips & Salsa', 
'Chocolate Milk', 
'Choir Boys', 
'Chopsticks', 
'Chorus Girls', 
'Christmas', 
'Churches', 
'Chutes & Ladders', 
'Cigarette Burns', 
'Cigarettes', 
'Cinco de Mayo', 
'Cinderella', 
'Cindy Crawford', 
'Circus Peanuts', 
'Clark Gable', 
'Claude Monet', 
'Clay', 
'Cleaning The Bathroom', 
'Cleaning Your Room', 
'Cleopatra', 
'Cleveland', 
'Climbing A Ladder', 
'Climbing A Tree', 
'Clint Eastwood', 
'Cloned Sheep', 
'Clouds', 
'Clowns', 
'Cocaine', 
'Cockles & Mussels', 
'Cockroaches', 
'Coconuts', 
'Coffee', 
'Cold Pizza', 
'Colin Powell', 
'Collection Shells', 
'Comic Books', 
'Communists', 
'Commuting', 
'Computer Hackers', 
'Computers', 
'Confucius', 
'Conspiracy Theories', 
'Construction Workers', 
'Convenience Stores', 
'Cookies', 
'Cooking Dinner', 
'Cops & Robbers', 
'Coral Reef', 
'Corn Fields', 
'Corn Flakes', 
'Corn On The Cob', 
'Corned Beef & Cabbage', 
'Corrugated Cardboard', 
'Corvettes', 
'Cottage Cheese', 
'Cotton Candy', 
'Coughing & Sneezing', 
'Count Dracula', 
'Country Music', 
'Cow-Pies', 
'Cowboys', 
'Cowboys & Indians', 
'Cows', 
'Crabs', 
'Crash & Burn', 
'Crazy Horse', 
'Cream & Sugar', 
'Creamed Corn', 
'Crime & Punishment', 
'Crying', 
'Crystal Balls', 
'Cuba', 
'Cults', 
'Cup & Saucer', 
'Cupcakes', 
'Curds & Whey', 
'Currier & Ives', 
'Custer\'s Last Stand', 
'Cut & Curl', 
'Cutting The Grass', 
'D-Day, 1944', 
'Dallas & Fort Worth', 
'Dance Class', 
'Dancing', 
'Dandruff', 
'Danielle Steel', 
'Danny DeVito', 
'Dark Alleys', 
'Dark Alleys', 
'Darth Vader', 
'Dating', 
'David & Goliath', 
'David Letterman', 
'Day Care Centers', 
'Daytime TV', 
'Dead Fish', 
'Death & Dying', 
'Death & Taxes', 
'Death Valley', 
'Deer Hunting', 
'Demi Moore', 
'Democrats', 
'Dennis Rodman', 
'Denzel Washington', 
'Detroit', 
'Diamonds', 
'Dictionaries', 
'Dinner & A Movie', 
'Dinosaurs', 
'Dirt', 
'Dirty Diapers', 
'Dirty Dishes', 
'Dirty Socks', 
'Discos', 
'Discovering America', 
'Disneyland', 
'Divorce', 
'Doctors', 
'Doctors & Dentists', 
'Dollars & Cents', 
'Dodo Birds', 
'Dog Days', 
'Dog Food', 
'Doing The Dishes', 
'Doing The Hokey-Pokey', 
'Dolly Parton', 
'Dolphins', 
'Donuts', 
'Doorbells', 
'Double Thick Malts', 
'Dr. Evil', 
'Dr. Jekyll & Mr. Hyde', 
'Dr. Kevorkin', 
'Dr. Laura', 
'Dr. Seuss', 
'Dragons', 
'Drew Barrymore', 
'Drew Carey', 
'Drinking & Driving', 
'Driving A Car', 
'Driving Off A Cliff', 
'Drums', 
'Drunk Drivers', 
'Ducks', 
'Duct Tape', 
'Dumb Blonde Jokes', 
'Dumbo', 
'Dump Trucks', 
'Dungeons & Dragons', 
'Dustin Hoffman', 
'E-Mail', 
'Ear Wax', 
'Early Morning', 
'Ears', 
'Earthquakes', 
'Earwigs', 
'East Coast', 
'Eating Breakfast', 
'Ebony & Ivory', 
'Eddie Murphy', 
'Egg Rolls', 
'Eggplant', 
'Eggs', 
'Eleanor Roosevelt', 
'Electric Eels', 
'Electricity', 
'Elephants', 
'Elevators', 
'Elizabeth Taylor', 
'Elmo', 
'Elvis Presley', 
'Emergency Rooms', 
'Emily Dickinson', 
'Erasers', 
'Ernest Hemingway', 
'Europe', 
'Exorcism', 
'Exterminators', 
'Eyes', 
'Face Paint', 
'Factories', 
'Fairies', 
'Faith Hill', 
'Falling Down', 
'Fame & Fortune', 
'Family Reunions', 
'Family Vacations', 
'Family Values', 
'Farmers', 
'Farms', 
'Fast Food', 
'Fat', 
'Fear & Loathing', 
'Feathers', 
'Feminists', 
'Ferdinand & Isabella', 
'Fertilizer', 
'Festering Wounds', 
'Fidel Castro', 
'Field & Stream', 
'Finger Painting', 
'Fire', 
'Firefighters', 
'Firestorms', 
'Fireworks', 
'First Man On The Moon', 
'Fish & Chips', 
'Fishing', 
'Flags', 
'Flannel Shirts', 
'Flash Floods', 
'Flashlights', 
'Flies', 
'Flip-Flops', 
'Flipper', 
'Floods', 
'Florence Nightengale', 
'Flour', 
'Flower Gardens', 
'Flowers & Candy', 
'Fly Fishing', 
'Flying A Kite', 
'Flying Monkeys', 
'Folk Music', 
'Food & Shelter', 
'Food Poisoning', 
'Foot & Mouth', 
'Football', 
'Football Players', 
'Forest Fires', 
'Forever & Ever', 
'Fort Knox', 
'Fortune Cookies', 
'Fortune Teller', 
'Fourth Of July', 
'Frank Lloyd Wright'])

# Many characteristic cards come from http://www.com-www.com/applestoapples/
characteristic_cards = (
    ['Open', 'Blocky', 'Tubular', 'Awesome',
     'New', 'Flexible', 'Sunny', 'Cold', 'Slick', 'Absurd',
     'Abundant', 'Addictive', 'Adorable', 'Aged', 'Amazing',
     'American', 'Ancient', 'Animated', 'Annoying', 'Appetizing',
     'Armed & Dangerous', 'Arrogant', 'Attractive', 'Awesome',
     'Awful', 'Awkward', 'Bad', 'Bashful', 'Beautiful', 'Believable',
     'Best', 'Big', 'Big & Tall', 'Bitter', 'Black & Blue', 
     'Black & White', 'Bogus', 'Boisterous', 'Bold', 'Boring', 
     'Brains & Brawn', 'Brave', 'Bright', 'Bright & Shining', 'Brilliant',
     'Brutal', 'Bumpy', 'Busy', 'Calm', 'Careful', 'Caring', 'Casual',
     'Charismatic', 'Charming', 'Cheerful', 'Cheesy', 'Chewy',
     'Chubby', 'Chunky', 'Classic', 'Clean', 'Clear', 'Clever',
     'Clueless', 'Clumsy', 'Cold', 'Colorful', 'Comfortable',
     'Comical', 'Complicated', 'Conceited', 'Confused', 'Confusing',
     'Controversial', 'Cool', 'Cool & Collected', 'Corrupt', 'Cosmic',
     'Cosmopolitan', 'Costly', 'Courageous', 'Cowardly', 'Cozy',
     'Cranky', 'Crazed', 'Crazy', 'Creative', 'Creepy', 'Creepy & Crawly',
     'Crisp', 'Crisp & Delicious', 'Crooked', 'Cruel', 'Cruel & Unusual',
     'Crunchy', 'Cuddly', 'Curved', 'Cut & Dried', 'Cute',
     'Cute & Cuddly', 'Dainty', 'Dangerous', 'Daring', 'Dark',
     'Dashing', 'Dazed & Confused', 'Dead', 'Dead & Gone', 'Deadly',
     'Delicate', 'Delicious', 'Delightful', 'Demanding', 'Depressing',
     'Desperate', 'Devious', 'Difficult', 'Dignified', 'Dirty',
     'Disgusting', 'Distinguished', 'Disturbing', 'Down & Dirty',
     'Down & Out', 'Dramatic', 'Dreamy', 'Drunk & Disorderly', 'Dull',
     'Dumb', 'Dumb & Dumber', 'Dysfunctional', 'Earthy', 'Easy',
     'Eccentric', 'Edgy', 'Elderly', 'Elitist', 'Emotional',
     'Enchanting', 'Endangered', 'Energetic', 'Enjoyable', 'Enormous',
     'Entertaining', 'Eternal', 'European', 'Evil', 'Excellent',
     'Exciting', 'Exhausting', 'Expensive', 'Explosive', 'Exquisite',
     'Extreme', 'Fabulous', 'Fake', 'Famous', 'Fancy', 'Fantastic',
     'Fascinating', 'Fashionable', 'Fast', 'Fast & Furious', 'Fast & Loose',
     'Fat', 'Fat & Happy', 'Favorite', 'Fearful', 'Feminine',
     'Filthy', 'Fine', 'Flaky', 'Flamboyant', 'Flat', 'Flavorful',
     'Flawed', 'Flirtatious', 'Foot Loose & Fancy Free', 'Foreign',
     'Fragile', 'Fragrant', 'Frail', 'Frazzled', 'Fresh', 'Friendly',
     'Frightening', 'Frivolous', 'Funky', 'Fun', 'Funny', 'Furious',
     'Furry', 'Fuzzy', 'Gentle', 'Gigantic', 'Glamorous', 'Glitzy',
     'Global', 'Gloomy', 'Glorious', 'Good', 'Goody-Goody', 'Goofy',
     'Gorgeous', 'Graceful', 'Great', 'Grueling', 'Gruesome',
     'Grungy', 'Hairy', 'Hale & Hearty', 'Handsome', 'Handy', 'Happy',
     'Hard', 'Hardworking', 'Harmful', 'Harsh', 'Haunting',
     'Hazardous', 'Healthy', 'Heartless', 'Heavy', 'Helpful', 'High & Dry',
     'High & Low', 'High & Mighty', 'Hilarious', 'Hit & Miss',
     'Honest', 'Honorable', 'Hopeless', 'Horrible', 'Horrifying',
     'Hostile', 'Hot', 'Hot & Bothered', 'Hot & Cold', 'Hot & Heavy',
     'Hot & Muggy', 'Hot & Spicy', 'Hot & Sweaty', 'Huge', 'Humorous',
     'Icky', 'Ideal', 'Idiotic', 'Important', 'Industrious',
     'Influential', 'Innocent', 'Insane', 'Inspirational',
     'Insulting', 'Intelligent', 'Intense', 'Interesting',
     'Irresistible', 'Irritating', 'Jolly', 'Juicy', 'Kind', 'Large',
     'Lazy', 'Lean & Mean', 'Legendary', 'Lewd & Lascivious', 'Light',
     'Light & Fluffy', 'Little', 'Lively', 'Long', 'Long & Lean',
     'Loud', 'Loud & Clear', 'Lovable', 'Loving', 'Lucky', 'Lumpy',
     'Luscious', 'Luxurious', 'Magical', 'Manly', 'Masculine', 'Mean',
     'Meek', 'Meek & Mild', 'Melodramatic', 'Mesmerizing', 'Messy',
     'Mischievous', 'Miserable', 'Misunderstood', 'Modern', 'Mushy',
     'Mysterious', 'Mystical', 'Naive', 'Nasty', 'Natural', 'Naughty & Nice',
     'Neat', 'Neat & Clean', 'Neglected', 'Nerdy', 'New', 'New & Improved', 
     'Nice', 'Noisy', 'Normal', 'Nutty', 'Obnoxious',
     'Obscene', 'Odd', 'Offensive', 'Old', 'Old & Cranky', 'Old & Wise', 
     'On The Up & Up', 'Orderly', 'Ordinary', 'Organic',
     'Outrageous', 'Overwhelming', 'Painful', 'Pale', 'Pathetic',
     'Patriotic', 'Peaceful', 'Perfect', 'Perverse', 'Philosophical',
     'Phony', 'Plain', 'Plain & Simple', 'Playful', 'Pleasant', 'Plug & Play',
     'Plump & Tender', 'Polite', 'Poor', 'Popular',
     'Powerful', 'Practical', 'Pretty', 'Prim & Proper', 'Primitive',
     'Principled', 'Profound', 'Proud', 'Puffy', 'Pure', 'Quick',
     'Quick & Dirty', 'Quiet', 'Radiant', 'Radical', 'Rare', 'Raw',
     'Realistic', 'Refreshing', 'Refined', 'Relaxed', 'Relaxing',
     'Repulsive', 'Respectable', 'Responsible', 'Revolutionary',
     'Rich', 'Ridiculous', 'Risky', 'Rough', 'Rough & Ready', 'Round',
     'Sad', 'Saintly', 'Sappy', 'Scary', 'Scenic', 'Scented',
     'Secretive', 'Selfish', 'Sensational', 'Senseless', 'Sensitive',
     'Sensual', 'Serious', 'Sexy', 'Shaggy', 'Shallow', 'Sharp',
     'Shiny', 'Shiny', 'Shocking', 'Short', 'Short & Stout', 'Short & Sweet',
     'Shy', 'Sick & Tired', 'Sick & Twisted', 'Sickening',
     'Silent', 'Silky', 'Silly', 'Simple', 'Skillful', 'Skinny',
     'Slender', 'Slimy', 'Slippery', 'Sloppy', 'Slow', 'Slow & Steady', 
     'Sluggish', 'Small', 'Smart', 'Smelly', 'Smooth',
     'Smooth & Creamy', 'Snappy', 'Sneaky', 'Soft', 'Sophisticated',
     'Sour', 'Special', 'Speedy', 'Spic & Span', 'Spicy', 'Spiritual',
     'Spooky', 'Sporty', 'Spotless', 'Spunky', 'Square', 'Squeaky Clean', 
     'Stereotyped', 'Sticky', 'Stinky', 'Straight', 'Strange',
     'Strong', 'Stunning', 'Stupid', 'Sultry', 'Surprising', 'Sweet',
     'Swift', 'Swift & Sure', 'Talented', 'Tall', 'Tame', 'Tasty',
     'Technological', 'Temperamental', 'Tempting', 'Tender',
     'Terrible', 'Terrific', 'Thick', 'Thick & Chunky', 'Thin',
     'Thoughtful', 'Timeless', 'Tiny', 'Tormenting', 'Torn & Tattered',
     'Touch & Go', 'Touchy-Feely', 'Tough', 'Trashy',
     'Tried & True', 'True & Blue', 'Trustworthy', 'Twisted', 'Ugly',
     'Unbelievable', 'Unforgettable', 'Unhappy', 'Unhealthy',
     'Unnatural', 'Unreal', 'Unscrupulous', 'Unusual', 'Untamed', 'Up & Coming',
     'Up & Down', 'Useful', 'Useless', 'Vain', 'Valuable',
     'Violent', 'Virtuous', 'Visionary', 'Warm', 'Warm & Cozy', 'Warm & Fuzzy',
     'Wash & Wear', 'Weak', 'Weird', 'Wet', 'Whimsical',
     'Wicked', 'Wide', 'Wild', 'Wild & Wooly', 'Wired', 'Witty',
     'Woebegone', 'Wonderful', 'Worldly', 'Worthless', 'Young', 
     'Young & Restless', 'Yucky', 'Zany'] )
